Repository neicnordic/sensitive-data-archive, pull requests merged in 2024-07, with the labels that each got.

#929 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#948 [actions] update container pruning action
  .github/workflows/ghcr-actions.yml
Labels: bug, github_actions

#943 [SDA] add timestamp to MQ messages
  sda/internal/broker/broker.go
Labels: go, Summer task

#949 [download] ignore trailing slashes in ISS and JKU URLs
  sda-download/pkg/auth/auth.go
  sda-download/pkg/auth/auth_test.go
Labels: go, Summer task

#947 [Auth] server public key as a base64 encoded string
  sda/cmd/auth/info.go
  sda/cmd/auth/info_test.go
  sda/cmd/auth/main.go
Labels: go, Summer task

#942 [Integration tests] Bad messages and file errors
  .github/integration/tests/sda/91_bad_messages.sh
  .github/integration/tests/sda/92_handle_file_errors.sh
Labels: github_actions, Summer task

#944 [auth] Make the TTL of the resigned token configurable
  .github/integration/scripts/charts/values.yaml
  .github/integration/sda/config.yaml
  charts/sda-svc/Chart.yaml
  charts/sda-svc/README.md
  charts/sda-svc/templates/auth-deploy.yaml
  charts/sda-svc/values.yaml
  sda/cmd/auth/auth.md
  sda/cmd/auth/main.go
  sda/internal/config/config.go
  sda/internal/config/config_test.go
Labels: go, Summer task

#963 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr
