Repository neicnordic/sensitive-data-archive, pull requests merged in 2024-03, with the labels that each got.

#705 Bugfix/re-encrypt
  .github/integration/tests/sda/50_reencrypt_test.sh
  sda/cmd/reencrypt/reencrypt.go
  sda/cmd/reencrypt/reencrypt_test.go
Labels: bug

#716 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#718 update_dependabot
  .github/dependabot.yaml
Labels: bug

#723 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#729 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#731 remove from merge group
  .github/workflows/build_pr_container.yaml
  .github/workflows/codeql-analysis.yml
Labels: bug

#733 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#738 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#752 Hotfix: reencrypt tls configuration
  .github/integration/sda-posix-integration.yml
  sda/cmd/reencrypt/reencrypt.go
  sda/cmd/reencrypt/reencrypt_test.go
  sda/internal/helper/helper.go
Labels: bug, go

#754 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#755 Hotfix: [charts] [sda-svc]
  charts/sda-svc/Chart.yaml
  charts/sda-svc/templates/_helpers.yaml
  charts/sda-svc/templates/auth-deploy.yaml
Labels: bug

#759 [sync-api] Increase server timeout limits
  sda/cmd/syncapi/syncapi.go
Labels: bug

#765 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#766 Rename html template file to match what's in the code.
  sda/cmd/auth/frontend/templates/oidc.html
Labels: bug

#768 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#771 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#775 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr
