Repository neicnordic/sensitive-data-archive, pull requests merged in 2024-05, with the labels that each got.

#835 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#842 Update GO version to 1.22
  .github/workflows/code-linter.yaml
  .github/workflows/functionality.yml
  .github/workflows/test.yml
  sda-download/Dockerfile
  sda-download/go.mod
  sda/Dockerfile
  sda/go.mod
Labels: go

#851 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#854 Fix CodeQL failure
  sda-download/go.mod
  sda/go.mod
Labels: go, github_actions

#855 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#863 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#874 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#885 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr
