Repository neicnordic/sensitive-data-archive, pull requests merged in 2024-01, with the labels that each got.

#570 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#588 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#601 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#535 Store file errors in db
  .github/integration/tests/run_scripts.sh
  .github/integration/tests/sda/10_upload_test.sh
  .github/integration/tests/sda/11_api-getfiles_test.sh
  .github/integration/tests/sda/20_ingest-verify_test.sh
  .github/integration/tests/sda/22_error_test.sh
  .github/integration/tests/sda/30_backup-finalize_test.sh
  .github/integration/tests/sda/31_cancel_test2.sh
  .github/integration/tests/sda/40_mapper_test.sh
  .github/integration/tests/sda/45_sync_test.sh
  sda/cmd/api/api_test.go
  sda/cmd/finalize/finalize.go
  sda/cmd/ingest/ingest.go
  sda/cmd/s3inbox/proxy.go
  sda/cmd/verify/verify.go
  sda/internal/database/db_functions.go
  sda/internal/database/db_functions_test.go
  sda/internal/storage/storage.go
  sda/internal/storage/storage_test.go
Labels: enhancement, go

#602 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#614 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#620 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#619 [Hotfix] race condition related to `syncapi`
  .github/integration/tests/sda/32_test_race_condition.sh
  sda/cmd/finalize/finalize.go
Labels: bug, BigPicture

#625 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#622 Rabbitmq consumer timeout
  .github/integration/rabbitmq-federation.yml
  .github/integration/tests/rabbitmq/10_federation_test.sh
  .github/integration/tests/rabbitmq/20_configuration_test.sh
  charts/sda-mq/Chart.yaml
  charts/sda-mq/README.md
  charts/sda-mq/templates/statefulset.yaml
  charts/sda-mq/values.yaml
  rabbitmq/docker-entrypoint.sh
Labels: enhancement, FEGA, BigPicture

#627 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#628 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#637 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr
