Repository neicnordic/sensitive-data-archive, pull requests merged in 2024-02, with the labels that each got.

#639 Pull latest changes from `neicnordic/sda-download` repository
  sda-download/.github/integration/setup/common/10_services.sh
  sda-download/.github/integration/tests/common/50_check_endpoint.sh
  sda-download/.github/integration/tests/s3notls/52_check_endpoint.sh
  sda-download/.github/workflows/codeql-analysis.yml
  sda-download/.github/workflows/integration.yml
  sda-download/.github/workflows/publish.yml
  sda-download/.github/workflows/report.yml
  sda-download/.github/workflows/shellcheck.yml
  sda-download/.github/workflows/test.yml
  sda-download/api/api.go
  sda-download/api/middleware/README.md
  sda-download/api/middleware/middleware.go
  sda-download/api/middleware/middleware_test.go
  sda-download/api/s3/s3.go
  sda-download/api/sda/sda.go
  sda-download/api/sda/sda_test.go
  sda-download/cmd/main.go
  sda-download/dev_utils/compose.yml
  sda-download/dev_utils/config.yaml
  sda-download/gl-code-quality-report.json
  sda-download/go.mod
  sda-download/go.sum
  sda-download/internal/config/config.go
  sda-download/internal/config/config_test.go
  sda-download/internal/session/session.go
  sda-download/internal/session/session_test.go
  sda-download/pkg/auth/auth.go
Labels: MERGE

#641 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#644 Migrate to aws v2
  sda/cmd/s3inbox/proxy.go
  sda/cmd/s3inbox/s3inbox.go
  sda/go.mod
  sda/go.sum
  sda/internal/storage/storage.go
  sda/internal/storage/storage_test.go
Labels: Refactoring

#652 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#653 Update to GO 1.21
  .github/workflows/code-linter.yaml
  .github/workflows/functionality.yml
  .github/workflows/test.yml
  sda-auth/Dockerfile
  sda-auth/go.mod
  sda-auth/go.sum
  sda-download/Dockerfile
  sda-download/go.mod
  sda-download/go.sum
  sda/Dockerfile
  sda/go.mod
  sda/go.sum
Labels: go

#656 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#666 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#643 [s3inbox] do authentication before we start processing the request
  sda/cmd/s3inbox/proxy.go
  sda/cmd/s3inbox/proxy_test.go
  sda/internal/userauth/userauth.go
  sda/internal/userauth/userauth_test.go
Labels: Refactoring

#677 Update k8s versions used in the tests
  .github/workflows/build_pr_container.yaml
Labels: github_actions

#675 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#693 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr
