Repository neicnordic/sensitive-data-archive, pull requests merged in 2025-02, with the labels that each got.

#1352 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1357 bugfix/persist fileID over changes of the service instance
  sda/cmd/s3inbox/proxy.go
  sda/internal/database/db_functions.go
  sda/internal/database/db_functions_test.go
Labels: bug

#1373 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1381 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1411 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1429 Update Go to version 1.24
  .github/workflows/code-linter.yaml
  .github/workflows/test.yml
  sda-admin/go.mod
  sda-download/.github/workflows/test.yml
  sda-download/Dockerfile
  sda-download/go.mod
  sda/Dockerfile
  sda/go.mod
Labels: go
