Repository neicnordic/sensitive-data-archive, pull requests merged in 2025-05, with the labels that each got.

#1651 [Release v1] remove leftover sda-admin entries in the makefile
  Makefile
Labels: Release v1

#1641 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1652 [Release V1] backport PR#1521
  sda-sftp-inbox/pom.xml
Labels: java, Release v1

#1693 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1699 [release_v1] Release v1.0.0 of the helm charts
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
  charts/sda-svc/templates/doa-deploy.yaml
  charts/sda-svc/values.yaml
Labels: Release v1

#1700 Update go dependencies (release v2.0.0)
  sda-download/go.mod
  sda-download/go.sum
  sda/go.mod
  sda/go.sum
Labels: Release v2

#1682 Change sda-svc helm chart to use config file instead of ENVs (v2.0.0)
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
  charts/sda-svc/README.md
  charts/sda-svc/templates/_helpers.yaml
  charts/sda-svc/templates/api-deploy.yaml
  charts/sda-svc/templates/api-secrets.yaml
  charts/sda-svc/templates/auth-deploy.yaml
  charts/sda-svc/templates/auth-secrets.yaml
  charts/sda-svc/templates/download-deploy.yaml
  charts/sda-svc/templates/download-secrets.yaml
  charts/sda-svc/templates/finalize-deploy.yaml
  charts/sda-svc/templates/finalize-secrets.yaml
  charts/sda-svc/templates/ingest-deploy.yaml
  charts/sda-svc/templates/ingest-secrets.yaml
  charts/sda-svc/templates/intercept-deploy.yaml
  charts/sda-svc/templates/intercept-secrets.yaml
  charts/sda-svc/templates/mapper-deploy.yaml
  charts/sda-svc/templates/mapper-secrets.yaml
  charts/sda-svc/templates/re-encrypt-deploy.yaml
  charts/sda-svc/templates/reencrypt-secrets.yaml
  charts/sda-svc/templates/s3-inbox-deploy.yaml
  charts/sda-svc/templates/s3-inbox-secrets.yaml
  charts/sda-svc/templates/sync-deploy.yaml
  charts/sda-svc/templates/sync-secrets.yaml
  charts/sda-svc/templates/syncapi-deploy.yaml
  charts/sda-svc/templates/syncapi-secrets.yaml
  charts/sda-svc/templates/verify-deploy.yaml
  charts/sda-svc/templates/verify-secrets.yaml
  charts/sda-svc/values.yaml
Labels: Release v2
