Repository neicnordic/sensitive-data-archive, pull requests merged in 2025-07, with the labels that each got.

#1779 [release_v1][charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1792 [api] Optimize db queries for /users and /files
  sda/internal/database/db_functions.go
Labels: enhancement

#1812 [release_v1][charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1816 [tests] hardcode the crypt4gh version
  .github/integration/scripts/charts/dependencies.sh
Labels: bug, github_actions, Test

#1817 [release_v1][charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1819 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr
