Repository neicnordic/sensitive-data-archive, pull requests merged in 2025-04, with the labels that each got.

#1544 [release_v1]update .github folder to work on release_v1 branch
  .github/integration/scripts/make_certs.sh
  .github/integration/sda-doa-posix-outbox.yml
  .github/integration/sda-doa-s3-outbox.yml
  .github/integration/tests/doa/1.make_crypt4gh_files.sh
  .github/integration/tests/doa/2.insert_test_data.sh
  .github/integration/tests/doa/3.setup_outbox.sh
  .github/integration/tests/doa/4.run_tests.sh
  .github/workflows/build_pr_container.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/functionality.yml
  .github/workflows/publish_charts.yml
  .github/workflows/publish_container.yml
  .github/workflows/shellcheck.yml
  .github/workflows/test.yml
  .github/workflows/update_trivy_cache.yml
Labels: Release v1

#1542 [release_v1] prepare manual testing
  .github/integration/scripts/charts/Dockerfile
  .github/integration/scripts/charts/cleanup.sh
  .github/integration/scripts/charts/dependencies.sh
  .github/integration/scripts/charts/dependencies.yaml
  .github/integration/scripts/charts/deploy_charts.sh
  .github/integration/scripts/charts/import_local_images.sh
  .github/integration/scripts/charts/k3d.sh
  .github/integration/scripts/charts/values.yaml
  .github/integration/scripts/sign_jwt.sh
  .github/integration/sda/oidc.py
  .github/workflows/build_pr_container.yaml
  Makefile
  README.md
  charts/sda-svc/templates/api-deploy.yaml
  charts/sda-svc/templates/download-deploy.yaml
Labels: Release v1

#1526 Refactor ingest main work loop
  .github/integration/tests/sda/92_handle_file_errors.sh
  sda/cmd/api/api_test.go
  sda/cmd/ingest/ingest.go
  sda/cmd/ingest/ingest_test.go
  sda/cmd/sync/sync_test.go
  sda/cmd/verify/verify.go
  sda/internal/database/database.go
  sda/internal/database/db_functions.go
  sda/internal/database/db_functions_test.go
Labels: go, Refactoring

#1571 [s3inbox] store uploaded file size in db
  sda/cmd/s3inbox/proxy.go
  sda/cmd/s3inbox/proxy_test.go
Labels: go

#1592 [Docs] update the Development readme
  DEVELOPMENT.md
Labels: documentation

#1590 [release_v1] Update documentation to be centered on usage
  CONTRIBUTING.md
  GETTINGSTARTED.md
  LICENSE
  Makefile
  README.md
  charts/sda-svc/README.md
Labels: documentation, Release v1

#1637 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr
