Repository neicnordic/sensitive-data-archive, pull requests merged in 2025-08, with the labels that each got.

#1820 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1831 [release_v1][charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1797 [sda] remove string concatenations from SQL queries.
  sda/internal/database/db_functions.go
Labels: Refactoring

#1868 [release_v1][charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1879 [finalize] allow starting without backup enabled
  .github/integration/scripts/charts/deploy_charts.sh
  sda/internal/config/config.go
Labels: bug

#1904 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr

#1905 [charts] Bump version
  charts/sda-db/Chart.yaml
  charts/sda-mq/Chart.yaml
  charts/sda-svc/Chart.yaml
Labels: automated pr
